// +build !ignore_autogenerated

/*
Copyright 2018 Anevia.
*/
// Code generated by main. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnCluster) DeepCopyInto(out *CdnCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnCluster.
func (in *CdnCluster) DeepCopy() *CdnCluster {
	if in == nil {
		return nil
	}
	out := new(CdnCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CdnCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnClusterList) DeepCopyInto(out *CdnClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CdnCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnClusterList.
func (in *CdnClusterList) DeepCopy() *CdnClusterList {
	if in == nil {
		return nil
	}
	out := new(CdnClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CdnClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnClusterSource) DeepCopyInto(out *CdnClusterSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnClusterSource.
func (in *CdnClusterSource) DeepCopy() *CdnClusterSource {
	if in == nil {
		return nil
	}
	out := new(CdnClusterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnClusterSpec) DeepCopyInto(out *CdnClusterSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]CdnClusterSource, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnClusterSpec.
func (in *CdnClusterSpec) DeepCopy() *CdnClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CdnClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CdnClusterStatus) DeepCopyInto(out *CdnClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CdnClusterStatus.
func (in *CdnClusterStatus) DeepCopy() *CdnClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CdnClusterStatus)
	in.DeepCopyInto(out)
	return out
}
